import { existsSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { resolveComposeTargets } from './compose-routes';
import { EXAMPLE_PLUGINS_DIR, GENERATED_DIR, PLUGINS_DIR, PLUGIN_JOBS_FILE } from './paths';
import type { PluginEntry } from './types';

/** One manifest-declared job type, resolved to an importable composed path. */
export interface JobDecl {
  pluginId: string;
  type: string;
  maxAttempts?: number;
  /** Same shape as `ScheduleDecl.importPath` — see its doc comment. */
  importPath: string;
}

/**
 * Resolve every installed plugin's `jobs` declarations (RFC 0046) to
 * composed-route-tree import paths for `renderPluginJobs`. Exits with a
 * clear error when a declared entry module does not exist in the plugin
 * source — a job type with no reachable handler is worse than a failed
 * build, since it would silently fail every claimed job at runtime instead.
 */
export function collectPluginJobs(
  plugins: PluginEntry[],
  opts: { pluginsDir?: string; generatedDir?: string } = {},
): { decls: JobDecl[]; error?: string } {
  const pluginsDir = opts.pluginsDir ?? PLUGINS_DIR;
  const generatedDir = opts.generatedDir ?? GENERATED_DIR;
  const decls: JobDecl[] = [];

  for (const { dir, manifest, baseDir } of plugins) {
    if (!manifest.jobs) continue;
    const targets = resolveComposeTargets(manifest);
    if (!targets.ok) return { decls: [], error: targets.error };
    const baseTarget = targets.targets[0];
    for (const job of manifest.jobs) {
      const srcFile = join(baseDir ?? pluginsDir, dir, job.entry);
      if (!existsSync(srcFile)) {
        const dirLabel = baseDir === EXAMPLE_PLUGINS_DIR ? 'example-plugins' : 'plugins';
        return {
          decls: [],
          error:
            `[generate] plugin ${manifest.id} job "${job.type}" declares entry ` +
            `"${job.entry}" but that file does not exist in ${dirLabel}/${dir}/.`,
        };
      }
      const composedFile = join(baseTarget, job.entry.replace(/^app\//, ''));
      const importPath = relative(generatedDir, composedFile)
        .split(sep)
        .join('/')
        .replace(/\.ts$/, '');
      decls.push({
        pluginId: manifest.id,
        type: job.type,
        maxAttempts: job.maxAttempts,
        importPath,
      });
    }
  }

  return { decls };
}

/**
 * Emit `runtime/generated/plugin-jobs.ts` — static imports of every
 * manifest-declared job handler (RFC 0046), consumed by `runtime/src/jobs.ts`
 * via `runtime/instrumentation.ts`. Static imports (not dynamic paths) keep
 * the handlers inside the Next.js build graph so the standalone/production
 * bundle traces them like any route module — same rationale as
 * `renderPluginSchedules`.
 */
export function renderPluginJobs(decls: JobDecl[]): string {
  const imports = decls
    .map((d, i) => `import handler${String(i)} from ${JSON.stringify(d.importPath)};`)
    .join('\n');
  const entries = decls
    .map(
      (d, i) =>
        `  {\n    pluginId: ${JSON.stringify(d.pluginId)},\n    type: ${JSON.stringify(
          d.type,
        )},\n    maxAttempts: ${d.maxAttempts !== undefined ? String(d.maxAttempts) : 'undefined'},\n    handler: handler${String(i)},\n  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
${imports === '' ? '' : '\n' + imports + '\n'}
/**
 * The handler signature mirrors \`JobHandler\` from \`@sovereignfs/sdk\`
 * structurally so this file needs no imports when no plugin declares jobs
 * (the committed default state).
 */
export interface PluginJobDecl {
  pluginId: string;
  type: string;
  maxAttempts?: number;
  handler: (
    ctx: {
      pluginId: string;
      jobId: string;
      type: string;
      attempt: number;
      headers: Headers;
      reportProgress: (progress: number, message?: string) => Promise<void>;
    },
    payload: unknown,
  ) => Promise<void>;
}

/** Every manifest-declared job type across installed plugins (RFC 0046). */
export const PLUGIN_JOBS: PluginJobDecl[] = [${entries === '' ? '' : '\n' + entries + '\n'}];
`;
}

export function writePluginJobs(plugins: PluginEntry[]): void {
  const result = collectPluginJobs(plugins);
  if (result.error !== undefined) {
    console.error(result.error);
    process.exit(1);
  }
  writeFileSync(PLUGIN_JOBS_FILE, renderPluginJobs(result.decls));
}
