import { writeFileSync } from 'node:fs';
import { pluginCapabilityName } from '@sovereignfs/manifest';
import { PLUGIN_CAPABILITIES_FILE } from './paths';
import type { PluginEntry } from './types';

/**
 * Emit `runtime/generated/plugin-capabilities.ts` — the pre-computed list of
 * plugin-declared capabilities. The middleware imports `ALL_GRANTED_PLUGIN_CAPS`
 * to inject auto-granted capabilities into every authenticated session alongside
 * the platform-role capabilities (RFC 0022).
 */
export function renderPluginCapabilities(plugins: PluginEntry[]): string {
  interface CapDecl {
    pluginId: string;
    capName: string;
    namespacedCap: string;
    description?: string;
    defaultGrant: 'all' | 'none';
  }

  const decls: CapDecl[] = [];
  for (const { manifest } of plugins) {
    if (!manifest.capabilities) continue;
    for (const [capName, capDecl] of Object.entries(manifest.capabilities)) {
      decls.push({
        pluginId: manifest.id,
        capName,
        namespacedCap: pluginCapabilityName(manifest.id, capName),
        description: capDecl.description,
        defaultGrant: capDecl.defaultGrant ?? 'none',
      });
    }
  }

  const allGranted = decls.filter((d) => d.defaultGrant === 'all').map((d) => d.namespacedCap);

  const declsJson = JSON.stringify(
    decls.map((d) => ({
      pluginId: d.pluginId,
      capName: d.capName,
      namespacedCap: d.namespacedCap,
      ...(d.description !== undefined ? { description: d.description } : {}),
      defaultGrant: d.defaultGrant,
    })),
    null,
    2,
  );

  const allGrantedJson = JSON.stringify(allGranted, null, 2);

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.

export interface PluginCapabilityDecl {
  pluginId: string;
  capName: string;
  /** Fully-namespaced: \`<pluginId>:<capName>\` */
  namespacedCap: string;
  description?: string;
  defaultGrant: 'all' | 'none';
}

/** All plugin-declared capabilities across installed plugins. */
export const PLUGIN_CAPABILITIES: PluginCapabilityDecl[] = ${declsJson};

/**
 * Plugin capabilities with \`defaultGrant: 'all'\` — automatically granted to
 * every authenticated user. The middleware appends these to the platform-role
 * capabilities in the \`x-sovereign-user-capabilities\` header so
 * \`sdk.auth.hasCapability(session, '<pluginId>:<capName>')\` works without a
 * DB lookup (RFC 0022).
 */
export const ALL_GRANTED_PLUGIN_CAPS: string[] = ${allGrantedJson};
`;
}

export function writePluginCapabilities(plugins: PluginEntry[]): void {
  writeFileSync(PLUGIN_CAPABILITIES_FILE, renderPluginCapabilities(plugins));
}
