import { existsSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { resolveComposeTargets } from './compose-routes';
import { EXAMPLE_PLUGINS_DIR, GENERATED_DIR, PLUGINS_DIR, PLUGIN_SCHEDULES_FILE } from './paths';
import type { PluginEntry } from './types';

/** One manifest-declared schedule, resolved to an importable composed path. */
export interface ScheduleDecl {
  pluginId: string;
  scheduleId: string;
  intervalMinutes: number;
  /**
   * Module specifier relative to `runtime/generated/` (POSIX separators, no
   * `.ts` extension) pointing at the schedule's real entry module in the
   * plugin's own source tree (not its composed route-tree copy/symlink —
   * see the importPath comment in collectPluginSchedules for why).
   */
  importPath: string;
}

/**
 * Resolve every installed plugin's `schedules` declarations (RFC 0046 Phase 1)
 * to real-source import paths for `renderPluginSchedules`. Exits with a
 * clear error when a declared entry module does not exist in the plugin
 * source — a schedule that silently never runs is worse than a failed build.
 */
export function collectPluginSchedules(
  plugins: PluginEntry[],
  opts: { pluginsDir?: string; generatedDir?: string } = {},
): { decls: ScheduleDecl[]; error?: string } {
  const pluginsDir = opts.pluginsDir ?? PLUGINS_DIR;
  const generatedDir = opts.generatedDir ?? GENERATED_DIR;
  const decls: ScheduleDecl[] = [];

  for (const { dir, manifest, baseDir } of plugins) {
    if (!manifest.schedules) continue;
    // Validates the manifest's shell/routePrefix combination (e.g. overlay +
    // multi-segment routePrefix) — the composed target path itself is no
    // longer used below; see the importPath comment for why.
    const targets = resolveComposeTargets(manifest);
    if (!targets.ok) return { decls: [], error: targets.error };
    for (const sched of manifest.schedules) {
      const srcFile = join(baseDir ?? pluginsDir, dir, sched.entry);
      if (!existsSync(srcFile)) {
        const dirLabel = baseDir === EXAMPLE_PLUGINS_DIR ? 'example-plugins' : 'plugins';
        return {
          decls: [],
          error:
            `[generate] plugin ${manifest.id} schedule "${sched.id}" declares entry ` +
            `"${sched.entry}" but that file does not exist in ${dirLabel}/${dir}/.`,
        };
      }
      // Import the plugin's own real source file, not its composed
      // route-tree copy/symlink. A composed plugin dir is a *symlink* in
      // production (compose-routes.ts); TypeScript resolves a symlinked
      // file's own relative imports (e.g. a sibling `_lib/ids.ts`'s
      // `import 'nanoid'`) against the symlink's *apparent* location when
      // the file is reached via a relative path from outside the symlinked
      // tree — as this generated file's import always is — not the real
      // target directory the way Next's own route-file discovery does.
      // That silently breaks resolution of any node_modules package the
      // handler (transitively) imports that isn't independently redeclared
      // in runtime/package.json — found via a real production build failure
      // on the first plugin to combine a schedule with such an import. The
      // plugin's real source file has no such problem: it resolves exactly
      // like `pnpm --filter <plugin> typecheck` already does.
      const importPath = relative(generatedDir, srcFile).split(sep).join('/').replace(/\.ts$/, '');
      decls.push({
        pluginId: manifest.id,
        scheduleId: sched.id,
        intervalMinutes: sched.intervalMinutes,
        importPath,
      });
    }
  }

  return { decls };
}

/**
 * Emit `runtime/generated/plugin-schedules.ts` — static imports of every
 * manifest-declared schedule handler (RFC 0046 Phase 1), consumed by
 * `runtime/src/scheduler.ts` via `runtime/instrumentation.ts`. Static imports
 * (not dynamic paths) keep the handlers inside the Next.js build graph so the
 * standalone/production bundle traces them like any route module.
 */
export function renderPluginSchedules(decls: ScheduleDecl[]): string {
  const imports = decls
    .map((d, i) => `import handler${String(i)} from ${JSON.stringify(d.importPath)};`)
    .join('\n');
  const entries = decls
    .map(
      (d, i) =>
        `  {\n    pluginId: ${JSON.stringify(d.pluginId)},\n    scheduleId: ${JSON.stringify(
          d.scheduleId,
        )},\n    intervalMinutes: ${String(d.intervalMinutes)},\n    handler: handler${String(i)},\n  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
${imports === '' ? '' : '\n' + imports + '\n'}
/**
 * The handler signature mirrors \`ScheduleHandler\` from \`@sovereignfs/sdk\`
 * structurally so this file needs no imports when no plugin declares
 * schedules (the committed default state).
 */
export interface PluginScheduleDecl {
  pluginId: string;
  scheduleId: string;
  intervalMinutes: number;
  handler: (ctx: { pluginId: string; scheduleId: string; headers: Headers }) => Promise<void>;
}

/** Every manifest-declared schedule across installed plugins (RFC 0046 Phase 1). */
export const PLUGIN_SCHEDULES: PluginScheduleDecl[] = [${
    entries === '' ? '' : '\n' + entries + '\n'
  }];
`;
}

export function writePluginSchedules(plugins: PluginEntry[]): void {
  const result = collectPluginSchedules(plugins);
  if (result.error !== undefined) {
    console.error(result.error);
    process.exit(1);
  }
  writeFileSync(PLUGIN_SCHEDULES_FILE, renderPluginSchedules(result.decls));
}
