import { existsSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { resolveComposeTargets } from './compose-routes';
import { EXAMPLE_PLUGINS_DIR, GENERATED_DIR, PLUGINS_DIR, PLUGIN_SCHEDULES_FILE } from './paths';
import type { PluginEntry } from './types';

/** One manifest-declared schedule, resolved to an importable composed path. */
export interface ScheduleDecl {
  pluginId: string;
  scheduleId: string;
  intervalMinutes: number;
  /**
   * Module specifier relative to `runtime/generated/` (POSIX separators, no
   * `.ts` extension) pointing at the schedule's composed entry module inside
   * the runtime route tree.
   */
  importPath: string;
}

/**
 * Resolve every installed plugin's `schedules` declarations (RFC 0046 Phase 1)
 * to composed-route-tree import paths for `renderPluginSchedules`. Exits with
 * a clear error when a declared entry module does not exist in the plugin
 * source — a schedule that silently never runs is worse than a failed build.
 */
export function collectPluginSchedules(
  plugins: PluginEntry[],
  opts: { pluginsDir?: string; generatedDir?: string } = {},
): { decls: ScheduleDecl[]; error?: string } {
  const pluginsDir = opts.pluginsDir ?? PLUGINS_DIR;
  const generatedDir = opts.generatedDir ?? GENERATED_DIR;
  const decls: ScheduleDecl[] = [];

  for (const { dir, manifest, baseDir } of plugins) {
    if (!manifest.schedules) continue;
    const targets = resolveComposeTargets(manifest);
    if (!targets.ok) return { decls: [], error: targets.error };
    // targets[0] is the plugin's primary composed app dir at every shell
    // (default/overlay → the (plugins) group; minimal → the (minimal) group).
    const baseTarget = targets.targets[0];
    for (const sched of manifest.schedules) {
      const srcFile = join(baseDir ?? pluginsDir, dir, sched.entry);
      if (!existsSync(srcFile)) {
        const dirLabel = baseDir === EXAMPLE_PLUGINS_DIR ? 'example-plugins' : 'plugins';
        return {
          decls: [],
          error:
            `[generate] plugin ${manifest.id} schedule "${sched.id}" declares entry ` +
            `"${sched.entry}" but that file does not exist in ${dirLabel}/${dir}/.`,
        };
      }
      const composedFile = join(baseTarget, sched.entry.replace(/^app\//, ''));
      const importPath = relative(generatedDir, composedFile)
        .split(sep)
        .join('/')
        .replace(/\.ts$/, '');
      decls.push({
        pluginId: manifest.id,
        scheduleId: sched.id,
        intervalMinutes: sched.intervalMinutes,
        importPath,
      });
    }
  }

  return { decls };
}

/**
 * Emit `runtime/generated/plugin-schedules.ts` — static imports of every
 * manifest-declared schedule handler (RFC 0046 Phase 1), consumed by
 * `runtime/src/scheduler.ts` via `runtime/instrumentation.ts`. Static imports
 * (not dynamic paths) keep the handlers inside the Next.js build graph so the
 * standalone/production bundle traces them like any route module.
 */
export function renderPluginSchedules(decls: ScheduleDecl[]): string {
  const imports = decls
    .map((d, i) => `import handler${String(i)} from ${JSON.stringify(d.importPath)};`)
    .join('\n');
  const entries = decls
    .map(
      (d, i) =>
        `  {\n    pluginId: ${JSON.stringify(d.pluginId)},\n    scheduleId: ${JSON.stringify(
          d.scheduleId,
        )},\n    intervalMinutes: ${String(d.intervalMinutes)},\n    handler: handler${String(i)},\n  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
${imports === '' ? '' : '\n' + imports + '\n'}
/**
 * The handler signature mirrors \`ScheduleHandler\` from \`@sovereignfs/sdk\`
 * structurally so this file needs no imports when no plugin declares
 * schedules (the committed default state).
 */
export interface PluginScheduleDecl {
  pluginId: string;
  scheduleId: string;
  intervalMinutes: number;
  handler: (ctx: { pluginId: string; scheduleId: string; headers: Headers }) => Promise<void>;
}

/** Every manifest-declared schedule across installed plugins (RFC 0046 Phase 1). */
export const PLUGIN_SCHEDULES: PluginScheduleDecl[] = [${
    entries === '' ? '' : '\n' + entries + '\n'
  }];
`;
}

export function writePluginSchedules(plugins: PluginEntry[]): void {
  const result = collectPluginSchedules(plugins);
  if (result.error !== undefined) {
    console.error(result.error);
    process.exit(1);
  }
  writeFileSync(PLUGIN_SCHEDULES_FILE, renderPluginSchedules(result.decls));
}
