import { existsSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { resolveComposeTargets } from './compose-routes';
import { EXAMPLE_PLUGINS_DIR, GENERATED_DIR, PLUGINS_DIR, PLUGIN_EVENTS_FILE } from './paths';
import type { PluginEntry } from './types';

/** One manifest-declared event channel authorizer, resolved to an importable composed path. */
export interface EventAuthorizerDecl {
  pluginId: string;
  pattern: string;
  /**
   * Module specifier relative to `runtime/generated/` (POSIX separators, no
   * `.ts` extension) pointing at the authorizer's composed entry module
   * inside the runtime route tree.
   */
  importPath: string;
}

/**
 * Resolve every installed plugin's `events` declarations (RFC 0045) to
 * composed-route-tree import paths for `renderPluginEvents`. Exits with a
 * clear error when a declared entry module does not exist in the plugin
 * source — an authorizer that silently never runs is worse than a failed
 * build (and would otherwise fail closed silently at request time instead).
 */
export function collectPluginEvents(
  plugins: PluginEntry[],
  opts: { pluginsDir?: string; generatedDir?: string } = {},
): { decls: EventAuthorizerDecl[]; error?: string } {
  const pluginsDir = opts.pluginsDir ?? PLUGINS_DIR;
  const generatedDir = opts.generatedDir ?? GENERATED_DIR;
  const decls: EventAuthorizerDecl[] = [];

  for (const { dir, manifest, baseDir } of plugins) {
    if (!manifest.events) continue;
    const targets = resolveComposeTargets(manifest);
    if (!targets.ok) return { decls: [], error: targets.error };
    const baseTarget = targets.targets[0];
    for (const evt of manifest.events) {
      const srcFile = join(baseDir ?? pluginsDir, dir, evt.entry);
      if (!existsSync(srcFile)) {
        const dirLabel = baseDir === EXAMPLE_PLUGINS_DIR ? 'example-plugins' : 'plugins';
        return {
          decls: [],
          error:
            `[generate] plugin ${manifest.id} event pattern "${evt.pattern}" declares entry ` +
            `"${evt.entry}" but that file does not exist in ${dirLabel}/${dir}/.`,
        };
      }
      const composedFile = join(baseTarget, evt.entry.replace(/^app\//, ''));
      const importPath = relative(generatedDir, composedFile)
        .split(sep)
        .join('/')
        .replace(/\.ts$/, '');
      decls.push({
        pluginId: manifest.id,
        pattern: evt.pattern,
        importPath,
      });
    }
  }

  return { decls };
}

/**
 * Emit `runtime/generated/plugin-events.ts` — static imports of every
 * manifest-declared channel-authorizer handler (RFC 0045), consumed by
 * `runtime/src/event-authorization.ts`. Static imports (not dynamic paths)
 * keep the handlers inside the Next.js build graph so the standalone/
 * production bundle traces them like any route module.
 */
export function renderPluginEvents(decls: EventAuthorizerDecl[]): string {
  const imports = decls
    .map((d, i) => `import handler${String(i)} from ${JSON.stringify(d.importPath)};`)
    .join('\n');
  const entries = decls
    .map(
      (d, i) =>
        `  {\n    pluginId: ${JSON.stringify(d.pluginId)},\n    pattern: ${JSON.stringify(
          d.pattern,
        )},\n    handler: handler${String(i)},\n  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
${imports === '' ? '' : '\n' + imports + '\n'}
/**
 * The handler signature mirrors \`EventChannelAuthorizer\` from
 * \`@sovereignfs/sdk\` structurally so this file needs no imports when no
 * plugin declares an events authorizer (the committed default state).
 */
export interface PluginEventAuthorizerDecl {
  pluginId: string;
  pattern: string;
  handler: (ctx: {
    pluginId: string;
    userId: string;
    channel: string;
    headers: Headers;
  }) => Promise<boolean>;
}

/** Every manifest-declared event channel authorizer across installed plugins (RFC 0045). */
export const PLUGIN_EVENT_AUTHORIZERS: PluginEventAuthorizerDecl[] = [${
    entries === '' ? '' : '\n' + entries + '\n'
  }];
`;
}

export function writePluginEvents(plugins: PluginEntry[]): void {
  const result = collectPluginEvents(plugins);
  if (result.error !== undefined) {
    console.error(result.error);
    process.exit(1);
  }
  writeFileSync(PLUGIN_EVENTS_FILE, renderPluginEvents(result.decls));
}
