import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { REGISTRY_FILE } from './paths';
import type { PluginEntry } from './types';

export function renderRegistry(plugins: PluginEntry[]): string {
  const manifests = plugins.map((p) => p.manifest);
  return `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
import type { SovereignManifest } from '@sovereignfs/manifest';

export const registry: SovereignManifest[] = ${JSON.stringify(manifests, null, 2)};
`;
}

export function writeRegistry(plugins: PluginEntry[]): void {
  mkdirSync(dirname(REGISTRY_FILE), { recursive: true });
  const content = renderRegistry(plugins);
  writeFileSync(REGISTRY_FILE, content);
}
