import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default tseslint.config(
  // Ignore generated, build, and dependency output across the monorepo.
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/dist-tsc/**', // tsc -b project-reference build cache (Task 0.14) — see .gitignore
      '**/.next/**',
      '**/.turbo/**',
      '.remember/**', // remember plugin's per-machine scratch state (git-ignored)
      '.claude/worktrees/**', // ephemeral worktrees for spawned/isolated agent tasks (git-ignored)
      '**/next-env.d.ts', // generated by Next.js; uses triple-slash references
      // Composed plugin routes (symlinks/copies) — ignored, except the
      // hand-written exceptions un-ignored below. Mirrors
      // runtime/app/(platform)/(plugins)/.gitignore's own identical by-name
      // exception list (that file explains why each one is hand-written)
      // and runtime/tsconfig.json's matching `files` entries. Layered the
      // same way that .gitignore is (a single `*` per level, not a blanket
      // `**`, with the intermediate directory explicitly un-ignored before
      // re-ignoring one level deeper) because ESLint's ignore engine has the
      // same gitignore-inherited limitation: a `!`-negated pattern cannot
      // re-include a path whose parent directory an earlier pattern already
      // matched — confirmed directly (a single `!`-per-file negation against
      // the previous blanket `**` pattern silently left every file ignored)
      // before landing on this layered form.
      'runtime/app/(platform)/(plugins)/*',
      '!runtime/app/(platform)/(plugins)/layout.tsx',
      '!runtime/app/(platform)/(plugins)/@modal',
      'runtime/app/(platform)/(plugins)/@modal/*',
      '!runtime/app/(platform)/(plugins)/@modal/default.tsx',
      '!runtime/app/(platform)/(plugins)/@modal/error.tsx',
      '!runtime/app/(platform)/(plugins)/@modal/layout.tsx',
      '!runtime/app/(platform)/(plugins)/@modal/__tests__',
      'runtime/generated/**',
      // PWA service worker + Workbox bundles, generated by next-pwa at build.
      'runtime/public/sw.js',
      'runtime/public/workbox-*.js',
      'runtime/public/fallback-*.js',
      'runtime/public/worker-*.js',
      // Playwright e2e specs and config use their own type definitions and test
      // patterns that conflict with the project's TypeScript-strict + jsx-a11y rules.
      '__tests__/e2e/**',
      'playwright.config.ts',
      // Storybook config and generated static output.
      'packages/ui/.storybook/**',
      'packages/ui/storybook-static/**',
    ],
  },

  // Baseline JS recommended rules.
  js.configs.recommended,

  // TypeScript: recommended + strict (non-type-checked).
  ...tseslint.configs.strict,

  // Shared language options for all source files.
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
    rules: {
      // Allow intentionally-unused identifiers when prefixed with `_`
      // (e.g. required-by-signature stub params, ignored destructured fields).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // Accessibility: jsx-a11y recommended ruleset applied to all JSX/TSX files.
  // Enforces WCAG 2.1 AA-compatible patterns for platform and plugin code.
  {
    files: ['**/*.{jsx,tsx}'],
    plugins: { 'jsx-a11y': jsxA11y },
    rules: jsxA11y.flatConfigs.recommended.rules,
  },

  // SDK boundary rule (NFR-06): plugins may only use @sovereignfs/sdk and
  // @sovereignfs/ui. They must never reach into runtime internals or the
  // workspace-internal packages. This is load-bearing — never disable it.
  // Covers example-plugins/ too — a reference plugin demonstrating the wrong
  // boundary would be actively misleading.
  //
  // `plugins/console` is the one documented exception: it reaches
  // `runtime/src` directly via the `@/` alias (a platform-type plugin, not a
  // third-party one — see docs/architecture-rules.md) but still respects the
  // second pattern below (@sovereignfs/db/manifest/mailer stay forbidden even
  // there — see the comment in plugins/console/app/users/actions.ts). It gets
  // its own, narrower rule block below instead of being excluded outright,
  // so it doesn't silently lose that second restriction too.
  {
    files: ['plugins/**/*.{ts,tsx}', 'example-plugins/**/*.{ts,tsx}'],
    ignores: ['plugins/console/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              // `@/...` is runtime/tsconfig.json's own alias for the same
              // location `**/runtime/src` already blocks below — without
              // this, `@/src/whatever` reaches runtime internals completely
              // unflagged, since no-restricted-imports matches the literal
              // specifier text, not the resolved file path.
              group: ['@/*', '@/src', '@/src/*'],
              message: 'Plugins must not import runtime internals. Use @sovereignfs/sdk instead.',
            },
            {
              group: ['**/runtime/src', '**/runtime/src/*'],
              message: 'Plugins must not import runtime internals. Use @sovereignfs/sdk instead.',
            },
            {
              group: [
                '@sovereignfs/db',
                '@sovereignfs/db/*',
                '@sovereignfs/manifest',
                '@sovereignfs/manifest/*',
                '@sovereignfs/mailer',
                '@sovereignfs/mailer/*',
              ],
              message:
                'Plugins may only use @sovereignfs/sdk and @sovereignfs/ui, not internal platform packages.',
            },
          ],
        },
      ],
    },
  },

  // plugins/console's narrower boundary: still a platform-type plugin, not a
  // free pass — @sovereignfs/db/manifest/mailer stay forbidden (it goes
  // through runtime API routes for those, same as any other plugin would);
  // only the runtime/src (and its `@/` alias) restriction is lifted, since
  // Console is built and shipped as part of this same monorepo.
  {
    files: ['plugins/console/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '@sovereignfs/db',
                '@sovereignfs/db/*',
                '@sovereignfs/manifest',
                '@sovereignfs/manifest/*',
                '@sovereignfs/mailer',
                '@sovereignfs/mailer/*',
              ],
              message:
                'Plugins may only use @sovereignfs/sdk and @sovereignfs/ui, not internal platform packages.',
            },
          ],
        },
      ],
    },
  },

  // Disable stylistic rules that conflict with Prettier. Must come last.
  eslintConfigPrettier,
);
