import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default tseslint.config(
  // Ignore generated, build, and dependency output across the monorepo.
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/next-env.d.ts', // generated by Next.js; uses triple-slash references
      'runtime/app/(platform)/(plugins)/**', // composed plugin routes (symlinks/copies)
      'runtime/generated/**',
      // PWA service worker + Workbox bundles, generated by next-pwa at build.
      'runtime/public/sw.js',
      'runtime/public/workbox-*.js',
      'runtime/public/fallback-*.js',
      'runtime/public/worker-*.js',
      // Playwright e2e specs and config use their own type definitions and test
      // patterns that conflict with the project's TypeScript-strict + jsx-a11y rules.
      '__tests__/e2e/**',
      'playwright.config.ts',
      // Storybook config and generated static output.
      'packages/ui/.storybook/**',
      'packages/ui/storybook-static/**',
    ],
  },

  // Baseline JS recommended rules.
  js.configs.recommended,

  // TypeScript: recommended + strict (non-type-checked).
  ...tseslint.configs.strict,

  // Shared language options for all source files.
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
    rules: {
      // Allow intentionally-unused identifiers when prefixed with `_`
      // (e.g. required-by-signature stub params, ignored destructured fields).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // Accessibility: jsx-a11y recommended ruleset applied to all JSX/TSX files.
  // Enforces WCAG 2.1 AA-compatible patterns for platform and plugin code.
  {
    files: ['**/*.{jsx,tsx}'],
    plugins: { 'jsx-a11y': jsxA11y },
    rules: jsxA11y.flatConfigs.recommended.rules,
  },

  // SDK boundary rule (NFR-06): plugins may only use @sovereignfs/sdk and
  // @sovereignfs/ui. They must never reach into runtime internals or the
  // workspace-internal packages. This is load-bearing — never disable it.
  {
    files: ['plugins/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/runtime/src', '**/runtime/src/*'],
              message: 'Plugins must not import runtime internals. Use @sovereignfs/sdk instead.',
            },
            {
              group: [
                '@sovereignfs/db',
                '@sovereignfs/db/*',
                '@sovereignfs/manifest',
                '@sovereignfs/manifest/*',
                '@sovereignfs/mailer',
                '@sovereignfs/mailer/*',
              ],
              message:
                'Plugins may only use @sovereignfs/sdk and @sovereignfs/ui, not internal platform packages.',
            },
          ],
        },
      ],
    },
  },

  // Disable stylistic rules that conflict with Prettier. Must come last.
  eslintConfigPrettier,
);
