export { createClient, findWorkspaceRoot, resolveSqlitePath, type DbConfig } from './client';
export { platformBootstrapStatements } from './bootstrap';
export {
  createSqldClient,
  dropSqldNamespace,
  pluginNamespaceName,
  provisionSqldNamespace,
  sqldAdminUrl,
  sqldUrl,
} from './sqld';
export {
  DEFAULT_ROOT_PLUGIN_ID,
  DEFAULT_TENANT_ID,
  addUserGroupMember,
  bootstrapPlatformDb,
  countUnreadNotifications,
  createConsentGrant,
  createPluginStatusRowIfAbsent,
  createUserGroup,
  deleteUserGroup,
  dismissNotification,
  getAccountPrefs,
  getPluginAccessPolicy,
  getUserGroupById,
  getUserGroupUsage,
  grantDeviceConsent,
  grantPluginAccessGroup,
  grantPluginAccessUser,
  grantUserCapability,
  hasPluginAccessUserGrant,
  hasUserCapabilityGrant,
  getConsentGrant,
  getDefaultTenant,
  getInstanceId,
  getEmailDeliveryDiagnostics,
  getLastMigrationResult,
  getNotificationPrefs,
  getPlatformDb,
  deletePlatformSetting,
  getPlatformSetting,
  countAdminActivity,
  countUserActivity,
  listAdminActivity,
  listAllConsentGrants,
  listConsentGrants,
  listDeviceConsentGrants,
  listDisabledPluginIds,
  listPluginAccessGroups,
  listPluginAccessPolicies,
  listPluginAccessUsers,
  listPluginIdsGrantedToUser,
  listPluginIdsGrantedToUserGroups,
  listPluginStatus,
  listUserActivity,
  listUserCapabilityGrants,
  listUserGroupMembers,
  listUserGroups,
  listUserGroupsForUser,
  listUserNotifications,
  logDataAccess,
  markAllNotificationsRead,
  markNotificationRead,
  pingDb,
  recordActivity,
  recordEmailDelivery,
  recordPushDelivery,
  removeUserGroupMember,
  revokeConsentGrant,
  revokeDeviceConsent,
  revokePluginAccessGroup,
  revokePluginAccessUser,
  revokeUserCapability,
  sendNotification,
  seedAccountPrefsTimezone,
  setAccountPrefs,
  setNotificationPrefs,
  setPlatformSetting,
  setPluginAccessPolicy,
  setPluginEnabled,
  setTenantName,
  updateUserGroup,
  savePushSubscription,
  getPushSubscriptionsForUser,
  getPushSubscriptionsByUsers,
  deletePushSubscription,
  deleteUserPushSubscriptions,
  hasPushSubscription,
  deleteUserData,
  getActiveEntitlement,
  listUserEntitlements,
  listPluginEntitlements,
  listAllEntitlements,
  saveEntitlement,
  cancelEntitlement,
  getPaidPluginsWithoutEntitlement,
  getInstanceConfig,
  createPluginSecret,
  createStorageObject,
  createPluginConnection,
  createE2eeProfile,
  createE2eeDeviceEnrollment,
  disconnectPluginConnection,
  deletePluginProviderConfig,
  deletePluginSecret,
  deleteStorageObject,
  getPluginSecret,
  getPluginConnection,
  getPluginProviderConfig,
  getStorageObjectById,
  getStorageObjectByIdForToken,
  getStorageObjectByKey,
  getE2eeProfile,
  getE2eeRecoveryWrapper,
  hardDeleteUserPluginSecrets,
  hardDeleteUserStorageObjects,
  hardDeleteUserE2eeData,
  listAllPluginConnectionRefs,
  listAllPluginProviderConfigs,
  listPluginConnections,
  listPluginSecrets,
  listStorageObjects,
  listE2eeDeviceEnrollments,
  listUserPluginConnectionRefs,
  listUserPluginSecretRefs,
  markPluginConnectionError,
  markPluginConnectionUsed,
  markPluginProviderConfigChecked,
  markPluginSecretUsed,
  revokeE2eeDeviceEnrollment,
  setInstanceConfig,
  sumPluginStorageBytes,
  upsertE2eeRecoveryWrapper,
  upsertPluginProviderConfig,
  updatePluginConnection,
  updatePluginSecret,
  type AccountPrefsValue,
  type SidebarPluginEntry,
  type DeleteUserDataResult,
  type ActivityLogRow,
  type ConsentGrantRow,
  type DeviceConsentGrantRow,
  type EmailDeliveryClass,
  type EmailDeliveryDiagnostics,
  type EmailDeliveryLogRow,
  type EmailDeliveryStatus,
  type PushDeliveryLogRow,
  type PushDeliveryStatus,
  type EntitlementRow,
  type InstanceConfig,
  type RadiusPreset,
  type NotificationPrefsValue,
  type NotificationRow,
  type PlatformDb,
  type PluginConnectionAccessContext,
  type PluginConnectionRefRow,
  type PluginConnectionScope,
  type PluginConnectionStatus,
  type CreatePluginConnectionInput,
  type PluginConnectionListFilter,
  type PluginProviderConfigRow,
  type PluginProviderConfigStatus,
  type UpsertPluginProviderConfigInput,
  type UpdatePluginConnectionInput,
  type PluginSecretAccessContext,
  type PluginSecretRow,
  type PluginSecretScope,
  type PluginSecretRefRow,
  type CreatePluginSecretInput,
  type CreateStorageObjectInput,
  type PluginStorageObjectRow,
  type StorageAccessContext,
  type E2eeProfileRow,
  type CreateE2eeProfileInput,
  type E2eeRecoveryWrapperRow,
  type UpsertE2eeRecoveryWrapperInput,
  type E2eeDeviceEnrollmentRow,
  type CreateE2eeDeviceEnrollmentInput,
  type PushSubscriptionRow,
  type RecordActivityInput,
  type RecordEmailDeliveryInput,
  type RecordPushDeliveryInput,
  type SendNotificationInput,
  type UserGroupRow,
  type UserGroupMemberRow,
  type UserCapabilityGrantRow,
  type PluginAccessPolicyValue,
  type PluginAccessPolicyRow,
  type PluginAccessGrantRow,
  type PluginAccessGroupGrantRow,
} from './platform-db';
export { resolveDialect, type Dialect, type ResolvedDialect } from './dialect';
export {
  DbEncryptionConfigError,
  checkEncryptionMarker,
  clearEncryptionMarker,
  clearPluginEncryptionMarker,
  dbEncryptionKeyFromEnv,
  defaultDataDir,
  isEncryptionMarked,
  isPluginEncryptionMarked,
  openKeyedSqlite,
  resolvePluginEncryptionKey,
  writeEncryptionMarker,
  writePluginEncryptionMarker,
} from './sqlite-encryption';
export {
  decryptSqliteFileInPlace,
  encryptSqliteFileInPlace,
  listInstanceSqliteFiles,
} from './sqlite-migration';
export { runMigrations, runPluginMigrations, type MigrationResult } from './migrate';
export {
  dropPluginDb,
  getPluginDb,
  pluginMigrationsFolder,
  pluginMigrationsTableName,
  pluginSchemaName,
  pluginSqliteUrl,
  provisionPluginDb,
  type PluginDb,
} from './plugin-client';

export * as schema from './schema/sqlite';
export type {
  Tenant,
  NewTenant,
  User,
  NewUser,
  Session,
  NewSession,
  PluginStatus,
  NewPluginStatus,
  PlatformSetting,
  NewPlatformSetting,
  AccountPrefs,
  NewAccountPrefs,
  ConsentGrant,
  NewConsentGrant,
  DeviceConsentGrant,
  NewDeviceConsentGrant,
  DataAccessLogEntry,
  NewDataAccessLogEntry,
  ActivityLog,
  NewActivityLog,
  EmailDeliveryLog,
  NewEmailDeliveryLog,
  PushDeliveryLog,
  NewPushDeliveryLog,
  PluginStorageObject,
  NewPluginStorageObject,
  E2eeProfile,
  NewE2eeProfile,
  E2eeRecoveryWrapper,
  NewE2eeRecoveryWrapper,
  E2eeDeviceEnrollment,
  NewE2eeDeviceEnrollment,
  PluginSecret,
  NewPluginSecret,
  PluginConnection,
  NewPluginConnection,
  PluginProviderConfig,
  NewPluginProviderConfig,
  Notification,
  NewNotification,
  NotificationPrefs,
  NewNotificationPrefs,
  PushSubscription,
  NewPushSubscription,
  Entitlement,
  NewEntitlement,
  InstanceConfigRow,
  NewInstanceConfigRow,
} from './schema/sqlite/platform';
