export { createClient, findWorkspaceRoot, type DbConfig, type SqliteDb } from './client';
export { platformBootstrapStatements } from './bootstrap';
export { InvalidCronExpressionError, computeNextCronRun } from './cron';
export {
  createSqldClient,
  dropSqldNamespace,
  pluginNamespaceName,
  provisionSqldNamespace,
  sqldAdminUrl,
  sqldUrl,
} from './sqld';
export {
  DEFAULT_ROOT_PLUGIN_ID,
  DEFAULT_TENANT_ID,
  addUserGroupMember,
  bootstrapPlatformDb,
  countUnreadNotifications,
  createConsentGrant,
  createPluginStatusRowIfAbsent,
  createUserGroup,
  deleteUserGroup,
  dismissNotification,
  getAccountPrefs,
  getPluginAccessPolicy,
  getUserGroupById,
  getUserGroupUsage,
  grantDeviceConsent,
  grantPluginAccessGroup,
  grantPluginAccessUser,
  grantUserCapability,
  hasPluginAccessUserGrant,
  hasUserCapabilityGrant,
  getConsentGrant,
  getDefaultTenant,
  getInstanceId,
  getEmailDeliveryDiagnostics,
  getLastMigrationResult,
  getNotificationPrefs,
  getPlatformDb,
  deletePlatformSetting,
  getPlatformSetting,
  countAdminActivity,
  countUserActivity,
  listAdminActivity,
  listAllConsentGrants,
  listConsentGrants,
  listDeviceConsentGrants,
  listDisabledPluginIds,
  listPluginAccessGroups,
  listPluginAccessPolicies,
  listPluginAccessUsers,
  listPluginIdsGrantedToUser,
  listPluginIdsGrantedToUserGroups,
  listPluginStatus,
  listUserActivity,
  listUserCapabilityGrants,
  listUserGroupMembers,
  listUserGroups,
  listUserGroupsForUser,
  listUserNotifications,
  logDataAccess,
  markAllNotificationsRead,
  markNotificationRead,
  pingDb,
  recordActivity,
  recordEmailDelivery,
  recordPushDelivery,
  removeUserGroupMember,
  revokeConsentGrant,
  revokeDeviceConsent,
  revokePluginAccessGroup,
  revokePluginAccessUser,
  revokeUserCapability,
  sendNotification,
  seedAccountPrefsTimezone,
  setAccountPrefs,
  setNotificationPrefs,
  setPlatformSetting,
  setPluginAccessPolicy,
  setPluginEnabled,
  setTenantName,
  updateUserGroup,
  savePushSubscription,
  getPushSubscriptionsForUser,
  getPushSubscriptionsByUsers,
  deletePushSubscription,
  deleteUserPushSubscriptions,
  hasPushSubscription,
  savePushDeviceToken,
  getPushDeviceTokensForUser,
  deletePushDeviceToken,
  deletePushDeviceTokenByToken,
  touchPushDeviceToken,
  deleteUserData,
  getActiveEntitlement,
  listUserEntitlements,
  listPluginEntitlements,
  listAllEntitlements,
  saveEntitlement,
  cancelEntitlement,
  getPaidPluginsWithoutEntitlement,
  getInstanceConfig,
  getEmailCopy,
  setEmailCopy,
  deleteEmailCopy,
  createPluginSecret,
  createStorageObject,
  createPluginConnection,
  createE2eeProfile,
  createE2eeDeviceEnrollment,
  disconnectPluginConnection,
  deletePluginProviderConfig,
  deletePluginSecret,
  deleteStorageObject,
  getPluginSecret,
  getPluginConnection,
  getPluginProviderConfig,
  getStorageObjectById,
  getStorageObjectByIdForToken,
  getStorageObjectByKey,
  getE2eeProfile,
  getE2eeRecoveryWrapper,
  hardDeleteUserPluginSecrets,
  hardDeleteUserStorageObjects,
  hardDeleteUserE2eeData,
  listAllPluginConnectionRefs,
  listAllPluginProviderConfigs,
  listPluginConnections,
  listPluginSecrets,
  listStorageObjects,
  listE2eeDeviceEnrollments,
  listUserPluginConnectionRefs,
  listUserPluginSecretRefs,
  markPluginConnectionError,
  markPluginConnectionUsed,
  markPluginProviderConfigChecked,
  markPluginSecretUsed,
  revokeE2eeDeviceEnrollment,
  setInstanceConfig,
  sumPluginStorageBytes,
  upsertE2eeRecoveryWrapper,
  upsertPluginProviderConfig,
  updatePluginConnection,
  updatePluginSecret,
  checkWebhookReplay,
  type CheckWebhookReplayInput,
  createPluginHandoff,
  getPluginHandoff,
  consumePluginHandoff,
  type CreatePluginHandoffInput,
  type PluginHandoffRow,
  MAX_HANDOFF_PAYLOAD_BYTES,
  enqueueJob,
  scheduleJob,
  getJobById,
  listJobsForPlugin,
  cancelJob,
  cancelJobsForPlugin,
  updateJobProgress,
  claimNextJob,
  completeJobSuccess,
  completeJobFailure,
  getBackupJob,
  enqueueBackupJob,
  claimNextBackupJob,
  completeBackupJobSuccess,
  completeBackupJobFailure,
  listExpiredBackupJobs,
  reclaimStuckBackupJobs,
  getJobHealthSummary,
  type JobStatus,
  type PluginJobRow,
  type BackupJobRow,
  type EnqueueBackupJobInput,
  type EnqueueJobInput,
  type ScheduleJobInput,
  type CompleteJobFailureResult,
  type JobHealthSummary,
  type AccountPrefsValue,
  type SidebarPluginEntry,
  type DeleteUserDataResult,
  type ActivityLogRow,
  type ConsentGrantRow,
  type DeviceConsentGrantRow,
  type EmailDeliveryClass,
  type EmailDeliveryDiagnostics,
  type EmailDeliveryLogRow,
  type EmailDeliveryStatus,
  type PushDeliveryLogRow,
  type PushDeliveryStatus,
  type EntitlementRow,
  type InstanceConfig,
  type RadiusPreset,
  type EmailTemplateId,
  type NotificationPrefsValue,
  type NotificationRow,
  type PlatformDb,
  type PluginConnectionAccessContext,
  type PluginConnectionRefRow,
  type PluginConnectionScope,
  type PluginConnectionStatus,
  type CreatePluginConnectionInput,
  type PluginConnectionListFilter,
  type PluginProviderConfigRow,
  type PluginProviderConfigStatus,
  type UpsertPluginProviderConfigInput,
  type UpdatePluginConnectionInput,
  type PluginSecretAccessContext,
  type PluginSecretRow,
  type PluginSecretScope,
  type PluginSecretRefRow,
  type CreatePluginSecretInput,
  type CreateStorageObjectInput,
  type PluginStorageObjectRow,
  type StorageAccessContext,
  type E2eeProfileRow,
  type CreateE2eeProfileInput,
  type E2eeRecoveryWrapperRow,
  type UpsertE2eeRecoveryWrapperInput,
  type E2eeDeviceEnrollmentRow,
  type CreateE2eeDeviceEnrollmentInput,
  type PushSubscriptionRow,
  type PushDeviceTokenRow,
  type RecordActivityInput,
  type RecordEmailDeliveryInput,
  type RecordPushDeliveryInput,
  type SendNotificationInput,
  type UserGroupRow,
  type UserGroupMemberRow,
  type UserCapabilityGrantRow,
  type PluginAccessPolicyValue,
  type PluginAccessPolicyRow,
  type PluginAccessGrantRow,
  type PluginAccessGroupGrantRow,
} from './platform-db';
export { resolveDialect, type Dialect, type ResolvedDialect } from './dialect';
export {
  DbEncryptionConfigError,
  dbEncryptionKeyFromEnv,
  openKeyedSqlite,
} from './sqlite-encryption';
export {
  ENCRYPT_CLASSES_ENV,
  FIELD_KEK_ENV,
  FieldEncryptionConfigError,
  assertFieldEncryptionConfig,
  createFieldKeyRow,
  encryptClassesFromEnv,
  fieldKekFromEnv,
  getFieldKeyRow,
  getFieldKeyRowById,
  kekFingerprint,
  listFieldKeyRows,
  unwrapKeyMaterial,
  updateFieldKeyRowWrapped,
  wrapKeyMaterial,
  startHmacRotation,
  completeHmacRotation,
  listOpenHmacRotations,
  upsertFieldTableRegistration,
  listFieldTableRegistrations,
  getResealCheckpoint,
  upsertResealCheckpoint,
  clearResealCheckpoint,
  type FieldEncryptionKeyRow,
  type FieldTableRegistrationRow,
  type WrappedKeyPurpose,
} from './field-encryption';
export {
  SqldCutoverError,
  cutoverSqliteFileToSqld,
  previewSqliteFile,
  type CutoverTableResult,
} from './sqld-cutover';
export {
  PostgresMigrationError,
  coerceForPostgres,
  migratePluginSqliteToPostgres,
  previewSqliteFileForPostgres,
  type PostgresMigrationTableResult,
} from './postgres-migration';
export {
  PluginIsolationMigrationError,
  discoverPluginTables,
  migratePluginSharedToIsolated,
  previewPluginTables,
  sharedToIsolatedMigrationsTableName,
  type IsolationMigrationTableResult,
} from './plugin-isolation-migration';
export { runMigrations, runPluginMigrations, type MigrationResult } from './migrate';
export {
  dropPluginDb,
  getPluginDb,
  pluginMigrationsFolder,
  pluginMigrationsTableName,
  pluginSchemaName,
  provisionPluginDb,
  type PluginDb,
} from './plugin-client';

export * as schema from './schema/sqlite';
export type {
  Tenant,
  NewTenant,
  User,
  NewUser,
  Session,
  NewSession,
  PluginStatus,
  NewPluginStatus,
  PlatformSetting,
  NewPlatformSetting,
  AccountPrefs,
  NewAccountPrefs,
  ConsentGrant,
  NewConsentGrant,
  DeviceConsentGrant,
  NewDeviceConsentGrant,
  DataAccessLogEntry,
  NewDataAccessLogEntry,
  ActivityLog,
  NewActivityLog,
  EmailDeliveryLog,
  NewEmailDeliveryLog,
  PushDeliveryLog,
  NewPushDeliveryLog,
  PluginStorageObject,
  NewPluginStorageObject,
  E2eeProfile,
  NewE2eeProfile,
  E2eeRecoveryWrapper,
  NewE2eeRecoveryWrapper,
  E2eeDeviceEnrollment,
  NewE2eeDeviceEnrollment,
  PluginSecret,
  NewPluginSecret,
  PluginConnection,
  NewPluginConnection,
  PluginProviderConfig,
  NewPluginProviderConfig,
  Notification,
  NewNotification,
  NotificationPrefs,
  NewNotificationPrefs,
  PushSubscription,
  NewPushSubscription,
  Entitlement,
  NewEntitlement,
  InstanceConfigRow,
  NewInstanceConfigRow,
  WebhookReplay,
  NewWebhookReplay,
  PluginHandoff,
  NewPluginHandoff,
  PluginJob,
  NewPluginJob,
} from './schema/sqlite/platform';
