// Generated by scripts/generate-icons.ts — do not edit.
import type { ReactElement, SVGProps } from 'react';
import { HouseIcon } from './house';
import { SettingsIcon } from './settings';
import { LogOutIcon } from './log-out';
import { ChevronRightIcon } from './chevron-right';
import { ChevronLeftIcon } from './chevron-left';
import { ChevronDownIcon } from './chevron-down';
import { ChevronUpIcon } from './chevron-up';
import { XIcon } from './x';
import { CheckIcon } from './check';
import { PlusIcon } from './plus';
import { Trash2Icon } from './trash-2';
import { PencilIcon } from './pencil';
import { RotateCcwIcon } from './rotate-ccw';
import { SearchIcon } from './search';
import { UserIcon } from './user';
import { ShieldIcon } from './shield';
import { LockIcon } from './lock';
import { EyeIcon } from './eye';
import { EyeOffIcon } from './eye-off';
import { MailIcon } from './mail';
import { BellIcon } from './bell';
import { ActivityIcon } from './activity';
import { PackageIcon } from './package';
import { Grid2x2Icon } from './grid-2x2';
import { InfoIcon } from './info';
import { AlertTriangleIcon } from './alert-triangle';
import { CalendarIcon } from './calendar';

export type IconName =
  | 'house'
  | 'settings'
  | 'log-out'
  | 'chevron-right'
  | 'chevron-left'
  | 'chevron-down'
  | 'chevron-up'
  | 'x'
  | 'check'
  | 'plus'
  | 'trash-2'
  | 'pencil'
  | 'rotate-ccw'
  | 'search'
  | 'user'
  | 'shield'
  | 'lock'
  | 'eye'
  | 'eye-off'
  | 'mail'
  | 'bell'
  | 'activity'
  | 'package'
  | 'grid-2x2'
  | 'info'
  | 'alert-triangle'
  | 'calendar';

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement;

export const ICONS: Record<IconName, IconComponent> = {
  house: HouseIcon,
  settings: SettingsIcon,
  'log-out': LogOutIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-up': ChevronUpIcon,
  x: XIcon,
  check: CheckIcon,
  plus: PlusIcon,
  'trash-2': Trash2Icon,
  pencil: PencilIcon,
  'rotate-ccw': RotateCcwIcon,
  search: SearchIcon,
  user: UserIcon,
  shield: ShieldIcon,
  lock: LockIcon,
  eye: EyeIcon,
  'eye-off': EyeOffIcon,
  mail: MailIcon,
  bell: BellIcon,
  activity: ActivityIcon,
  package: PackageIcon,
  'grid-2x2': Grid2x2Icon,
  info: InfoIcon,
  'alert-triangle': AlertTriangleIcon,
  calendar: CalendarIcon,
};

export { HouseIcon } from './house';
export { SettingsIcon } from './settings';
export { LogOutIcon } from './log-out';
export { ChevronRightIcon } from './chevron-right';
export { ChevronLeftIcon } from './chevron-left';
export { ChevronDownIcon } from './chevron-down';
export { ChevronUpIcon } from './chevron-up';
export { XIcon } from './x';
export { CheckIcon } from './check';
export { PlusIcon } from './plus';
export { Trash2Icon } from './trash-2';
export { PencilIcon } from './pencil';
export { RotateCcwIcon } from './rotate-ccw';
export { SearchIcon } from './search';
export { UserIcon } from './user';
export { ShieldIcon } from './shield';
export { LockIcon } from './lock';
export { EyeIcon } from './eye';
export { EyeOffIcon } from './eye-off';
export { MailIcon } from './mail';
export { BellIcon } from './bell';
export { ActivityIcon } from './activity';
export { PackageIcon } from './package';
export { Grid2x2Icon } from './grid-2x2';
export { InfoIcon } from './info';
export { AlertTriangleIcon } from './alert-triangle';
export { CalendarIcon } from './calendar';
