import '@sovereignfs/ui/tokens.css';
import './globals.css';
import type { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';
import { Hanken_Grotesk, JetBrains_Mono } from 'next/font/google';
import { appleSplashScreens } from '@/src/apple-splash';
import { themeScript } from '@/src/theme-script';

const sans = Hanken_Grotesk({
  subsets: ['latin'],
  variable: '--sv-font-family',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--sv-font-family-mono',
  weight: ['400', '500'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Sovereign',
  description: 'Your self-hosted workspace.',
  // Installable PWA (SRS §3.11, PLT-09). The dynamic manifest route returns
  // the correct brand name from the DB; the static public/manifest.json is
  // kept for @ducanh2912/next-pwa build-time tooling only.
  manifest: '/api/manifest',
  appleWebApp: {
    capable: true,
    title: 'Sovereign',
    statusBarStyle: 'black-translucent',
    // Per-device iOS launch screens — without an exact media match iOS shows a
    // blank white flash on standalone launch. Generated by scripts/generate-splash.ts.
    startupImage: appleSplashScreens,
  },
  icons: {
    // /favicon.ico is a dynamic route (runtime/app/favicon.ico/route.ts, RFC
    // 0027 Phase 3) — it serves the operator's configured instance favicon
    // when set, falling back to the committed default transparently. Pointed
    // to unconditionally here rather than branching in this server component,
    // so no DB read is needed at layout render time.
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
};

export const viewport: Viewport = {
  // `themeColor` is intentionally omitted here. The pre-paint theme script owns
  // the `theme-color` meta so it can track the cookie-driven light/dark theme
  // (which can diverge from the OS scheme). Declaring it via `viewport` too makes
  // Next's metadata reconciler re-add its own copy on hydration, duplicating the
  // tag — see runtime/src/theme-script.ts.
  //
  // viewport-fit=cover allows content to extend into the notch/corner areas
  // (safe-area insets compensate in CSS with env(safe-area-inset-*)). Required
  // for the immersive black-translucent status bar on iOS standalone (RFC 0013).
  viewportFit: 'cover',
  // Disables two-finger pinch-to-zoom app-wide (native-app feel, no accidental
  // zoom mid-gesture on iOS). This reverses a prior explicit decision (see
  // docs/research/0011-ios-pwa-inspection-findings.md #1) made to preserve pinch-zoom
  // as a WCAG 1.4.4 (Resize Text) affordance for low-vision users — that
  // finding explicitly says not to do this without a replacement. Task 10.2's
  // in-app text-size control (Account → Preferences → Appearance,
  // --sv-text-size-scale) has since shipped as that replacement, so keeping
  // pinch-zoom disabled is now a deliberate, discharged tradeoff rather than
  // unmitigated debt — re-open this decision if the control is ever removed.
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    // The theme script sets data-theme on <html> before hydration, so the
    // attribute intentionally differs from the server markup —
    // suppressHydrationWarning scopes React's mismatch check off this element
    // (the standard theming pattern; suppression does not extend to children).
    <html lang="en" className={`${sans.variable} ${mono.variable}`} suppressHydrationWarning>
      <body>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {children}
      </body>
    </html>
  );
}
