import {
  existsSync,
  lstatSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { SovereignManifest } from '@sovereignfs/manifest';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  collectPluginEnv,
  collectPluginSchedules,
  duplicateApiProviders,
  duplicatePluginIds,
  linkOrCopyTarget,
  pruneGeneratedEntries,
  pruneStalePluginIcons,
  renderPluginCapabilities,
  renderPluginEnv,
  renderPluginSchedules,
  renderRegistry,
  resolveComposeTargets,
  sortPluginEntries,
  type EnvDecl,
  type PluginEntry,
} from '../generate-registry';

function manifest(overrides: Partial<SovereignManifest> = {}): SovereignManifest {
  return {
    schemaVersion: 1,
    id: 'com.example.plugin',
    name: 'Example Plugin',
    version: '1.0.0',
    type: 'community',
    runtime: 'native',
    routePrefix: '/example',
    permissions: [],
    compatibility: { minPlatformVersion: '0.0.0' },
    ...overrides,
  };
}

function entry(dir: string, overrides: Partial<SovereignManifest> = {}): PluginEntry {
  return { dir, manifest: manifest(overrides) };
}

describe('resolveComposeTargets', () => {
  const dirs = {
    platformPluginsDir: '/tmp/runtime/app/(platform)/(plugins)',
    modalDir: '/tmp/runtime/app/(platform)/(plugins)/@modal',
    minimalDir: '/tmp/runtime/app/(minimal)',
  };

  it('rejects multi-segment route prefixes for overlay plugins', () => {
    const result = resolveComposeTargets(
      manifest({ id: 'com.example.overlay', shell: 'overlay', routePrefix: '/admin/reports' }),
      dirs,
    );

    expect(result.ok).toBe(false);
    expect(result.targets).toEqual([]);
    expect(result.error).toContain('multi-segment');
    expect(result.error).toContain('/admin/reports');
  });

  it('accepts multi-segment route prefixes for minimal plugins', () => {
    const result = resolveComposeTargets(
      manifest({ id: 'com.example.minimal', shell: 'minimal', routePrefix: '/kiosk/display' }),
      dirs,
    );

    expect(result.ok).toBe(true);
    expect(result.targets).toEqual(['/tmp/runtime/app/(minimal)/kiosk/display']);
  });
});

describe('plugin generation guards', () => {
  it('detects duplicate apiProvider manifests before route generation', () => {
    const duplicates = duplicateApiProviders([
      entry('a', { id: 'com.example.api-a', apiProvider: true }),
      entry('b', { id: 'com.example.api-b', apiProvider: true }),
      entry('c', { id: 'com.example.regular' }),
    ]);

    expect(duplicates.map((plugin) => plugin.id)).toEqual([
      'com.example.api-a',
      'com.example.api-b',
    ]);
  });

  it('sorts plugin manifests deterministically by manifest id', () => {
    const sorted = sortPluginEntries([
      entry('z-dir', { id: 'com.example.zeta' }),
      entry('a-dir', { id: 'com.example.alpha' }),
      entry('m-dir', { id: 'com.example.middle' }),
    ]);

    expect(sorted.map((plugin) => plugin.manifest.id)).toEqual([
      'com.example.alpha',
      'com.example.middle',
      'com.example.zeta',
    ]);
    expect(sorted.map((plugin) => plugin.dir)).toEqual(['a-dir', 'm-dir', 'z-dir']);
  });

  // Guards against a real clone (plugins/<id>) coexisting with a personal
  // plugins/<id>.local dev override — both declare the same manifest id,
  // which install-plugins.ts's isPluginInstalled() now prevents at the
  // source, but this is a second line of defense so any other cause (e.g. two
  // differently-named directories both declaring the same id by mistake)
  // fails loudly at generate time instead of producing a duplicate registry
  // entry (a broken React key in the nav rail at runtime).
  it('detects two directories declaring the same manifest id', () => {
    const duplicates = duplicatePluginIds([
      entry('sovereign-tasks', { id: 'fs.sovereign.tasks' }),
      entry('sovereign-tasks.local', { id: 'fs.sovereign.tasks' }),
      entry('console', { id: 'fs.sovereign.console' }),
    ]);

    expect(Object.fromEntries(duplicates)).toEqual({
      'fs.sovereign.tasks': ['sovereign-tasks', 'sovereign-tasks.local'],
    });
  });

  it('reports no duplicates when every manifest id is unique', () => {
    const duplicates = duplicatePluginIds([
      entry('a', { id: 'com.example.a' }),
      entry('b', { id: 'com.example.b' }),
    ]);

    expect(duplicates.size).toBe(0);
  });
});

describe('generated TypeScript artifacts', () => {
  it('renders the registry from sorted manifest order', () => {
    const sorted = sortPluginEntries([
      entry('z-dir', { id: 'com.example.zeta' }),
      entry('a-dir', { id: 'com.example.alpha' }),
    ]);

    const content = renderRegistry(sorted);

    expect(content).toContain('AUTO-GENERATED by scripts/generate-registry.ts');
    expect(content.indexOf('"id": "com.example.alpha"')).toBeLessThan(
      content.indexOf('"id": "com.example.zeta"'),
    );
  });

  it('renders plugin capabilities and all-granted capabilities deterministically', () => {
    const content = renderPluginCapabilities([
      entry('notes', {
        id: 'com.example.notes',
        capabilities: {
          'read-notes': { description: 'Read notes', defaultGrant: 'all' },
          'write-notes': { description: 'Write notes' },
        },
      }),
    ]);

    expect(content).toContain('"namespacedCap": "com.example.notes:read-notes"');
    expect(content).toContain('"namespacedCap": "com.example.notes:write-notes"');
    expect(content).toContain('"defaultGrant": "none"');
    expect(content).toContain(
      'export const ALL_GRANTED_PLUGIN_CAPS: string[] = [\n  "com.example.notes:read-notes"\n];',
    );
  });
});

describe('plugin env generation', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-env-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('does not embed secret env default values in generated output', () => {
    const content = renderPluginEnv([
      {
        pluginId: 'com.example.secret',
        key: 'TOKEN',
        namespacedKey: 'SV_PLUGIN_COM_EXAMPLE_SECRET_TOKEN',
        required: true,
        secret: true,
        scope: 'runtime',
        defaultValue: 'do-not-embed',
      },
    ]);

    expect(content).toContain('"secret": true');
    expect(content).toContain('"SV_PLUGIN_COM_EXAMPLE_SECRET_TOKEN"');
    expect(content).not.toContain('do-not-embed');
  });

  it('uses plugin .env values only as non-secret dev defaults', () => {
    mkdirSync(join(root, 'notes'));
    writeFileSync(join(root, 'notes', '.env'), 'PUBLIC_LABEL=Local label\nTOKEN=plain-secret\n');

    const allowed = collectPluginEnv(
      [
        entry('notes', {
          id: 'com.example.notes',
          env: {
            PUBLIC_LABEL: {
              description: 'Development label',
              scope: 'runtime',
            },
          },
        }),
      ],
      root,
    );

    expect(allowed.ok).toBe(true);
    expect(allowed.decls).toMatchObject([
      {
        pluginId: 'com.example.notes',
        key: 'PUBLIC_LABEL',
        defaultValue: 'Local label',
        secret: false,
      } satisfies Partial<EnvDecl>,
    ]);

    const rejected = collectPluginEnv(
      [
        entry('notes', {
          id: 'com.example.notes',
          env: {
            TOKEN: {
              description: 'Secret token',
              required: true,
              secret: true,
              scope: 'runtime',
            },
          },
        }),
      ],
      root,
    );

    expect(rejected.ok).toBe(false);
    expect(rejected.error).toContain('marked secret');
    expect(rejected.error).toContain('plugins/notes/.env');
  });
});

describe('linkOrCopyTarget — dev copies, production symlinks', () => {
  let root: string;
  let src: string;
  let dest: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-compose-'));
    src = join(root, 'plugin-app');
    dest = join(root, 'composed');
    mkdirSync(src);
    writeFileSync(join(src, 'page.tsx'), 'export default function Page() {}');
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('dev: copies files into a real directory, not a symlink', () => {
    linkOrCopyTarget(src, dest, false);

    expect(lstatSync(dest).isSymbolicLink()).toBe(false);
    expect(existsSync(join(dest, 'page.tsx'))).toBe(true);
    expect(readFileSync(join(dest, 'page.tsx'), 'utf8')).toContain('export default');
  });

  it('dev: re-running only touches files that actually changed', () => {
    linkOrCopyTarget(src, dest, false);
    const firstCopyMtime = lstatSync(join(dest, 'page.tsx')).mtimeMs;

    // Re-run with no source change — the unchanged file must not be rewritten
    // (rewriting would spuriously invalidate Next's dev route watcher).
    linkOrCopyTarget(src, dest, false);
    expect(lstatSync(join(dest, 'page.tsx')).mtimeMs).toBe(firstCopyMtime);
  });

  it('production: creates a real symlink to the plugin source, not a copy', () => {
    linkOrCopyTarget(src, dest, true);

    expect(lstatSync(dest).isSymbolicLink()).toBe(true);
    // Resolves back to the plugin's own app/ — this is exactly what lets a
    // composed plugin's imports find its own node_modules at build time.
    expect(existsSync(join(dest, 'page.tsx'))).toBe(true);
    expect(readFileSync(join(dest, 'page.tsx'), 'utf8')).toContain('export default');
  });

  it('production: replaces a stale copy left over from a previous dev run', () => {
    linkOrCopyTarget(src, dest, false); // dev leaves a real directory
    expect(lstatSync(dest).isSymbolicLink()).toBe(false);

    linkOrCopyTarget(src, dest, true); // production must replace it with a symlink
    expect(lstatSync(dest).isSymbolicLink()).toBe(true);
  });

  it('dev: replaces a stale symlink left over from a previous production run', () => {
    linkOrCopyTarget(src, dest, true); // production leaves a symlink
    expect(lstatSync(dest).isSymbolicLink()).toBe(true);

    linkOrCopyTarget(src, dest, false); // dev must replace it with a real directory
    expect(lstatSync(dest).isSymbolicLink()).toBe(false);
    expect(existsSync(join(dest, 'page.tsx'))).toBe(true);
  });
});

describe('generated artifact pruning', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-prune-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('prunes stale generated routes while preserving active and committed entries', () => {
    mkdirSync(join(root, 'active'));
    mkdirSync(join(root, 'stale'));
    writeFileSync(join(root, 'layout.tsx'), 'layout');

    pruneGeneratedEntries(root, new Set(['active']), { keep: new Set(['layout.tsx']) });

    expect(existsSync(join(root, 'active'))).toBe(true);
    expect(existsSync(join(root, 'layout.tsx'))).toBe(true);
    expect(existsSync(join(root, 'stale'))).toBe(false);
  });

  it('prunes only stale generated modal routes', () => {
    mkdirSync(join(root, '(.)active'));
    mkdirSync(join(root, '(.)stale'));
    writeFileSync(join(root, 'default.tsx'), 'default');

    pruneGeneratedEntries(root, new Set(['(.)active']), { onlyPrefix: '(.)' });

    expect(existsSync(join(root, '(.)active'))).toBe(true);
    expect(existsSync(join(root, 'default.tsx'))).toBe(true);
    expect(existsSync(join(root, '(.)stale'))).toBe(false);
  });

  it('prunes stale generated plugin icons', () => {
    writeFileSync(join(root, 'com.example.active.svg'), '<svg />');
    writeFileSync(join(root, 'com.example.stale.svg'), '<svg />');

    pruneStalePluginIcons(root, new Set(['com.example.active']));

    expect(existsSync(join(root, 'com.example.active.svg'))).toBe(true);
    expect(existsSync(join(root, 'com.example.stale.svg'))).toBe(false);
  });
});

describe('plugin schedules generation', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-schedules-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  function scheduleEntry(dir: string, overrides: Partial<SovereignManifest> = {}): PluginEntry {
    // A real entry file so collectPluginSchedules's existence check passes.
    mkdirSync(join(root, dir, 'app', '_jobs'), { recursive: true });
    writeFileSync(join(root, dir, 'app', '_jobs', 'sync.ts'), 'export default async () => {};');
    return entry(dir, {
      schedules: [{ id: 'sync', intervalMinutes: 5, entry: 'app/_jobs/sync.ts' }],
      ...overrides,
    });
  }

  it('resolves a schedule to a composed-route-tree import path', () => {
    const generatedDir = join(root, 'runtime', 'generated');
    const result = collectPluginSchedules([scheduleEntry('example')], {
      pluginsDir: root,
      generatedDir,
    });

    expect(result.error).toBeUndefined();
    expect(result.decls).toHaveLength(1);
    const decl = result.decls[0];
    expect(decl?.pluginId).toBe('com.example.plugin');
    expect(decl?.scheduleId).toBe('sync');
    expect(decl?.intervalMinutes).toBe(5);
    // Relative from runtime/generated into the composed (plugins) group,
    // extension stripped so it is a valid import specifier.
    expect(decl?.importPath).toMatch(/^\.\..*\(plugins\)\/example\/_jobs\/sync$/);
    expect(decl?.importPath.endsWith('.ts')).toBe(false);
  });

  it('errors when a declared entry module does not exist', () => {
    const result = collectPluginSchedules(
      [
        entry('example', {
          schedules: [{ id: 'sync', intervalMinutes: 5, entry: 'app/_jobs/missing.ts' }],
        }),
      ],
      { pluginsDir: root, generatedDir: join(root, 'runtime', 'generated') },
    );

    expect(result.error).toContain('missing.ts');
    expect(result.decls).toHaveLength(0);
  });

  it('skips plugins without schedules', () => {
    const result = collectPluginSchedules([entry('plain')], {
      pluginsDir: root,
      generatedDir: join(root, 'runtime', 'generated'),
    });
    expect(result.error).toBeUndefined();
    expect(result.decls).toHaveLength(0);
  });

  it('renders an importing module for declared schedules', () => {
    const content = renderPluginSchedules([
      {
        pluginId: 'com.example.plugin',
        scheduleId: 'sync',
        intervalMinutes: 5,
        importPath: '../app/(platform)/(plugins)/example/_jobs/sync',
      },
    ]);

    expect(content).toContain('AUTO-GENERATED by scripts/generate-registry.ts');
    expect(content).toContain(
      'import handler0 from "../app/(platform)/(plugins)/example/_jobs/sync";',
    );
    expect(content).toContain('pluginId: "com.example.plugin"');
    expect(content).toContain('scheduleId: "sync"');
    expect(content).toContain('intervalMinutes: 5');
    expect(content).toContain('handler: handler0');
  });

  it('renders an import-free module when no plugin declares schedules', () => {
    const content = renderPluginSchedules([]);
    expect(content).not.toContain('import ');
    expect(content).toContain('export const PLUGIN_SCHEDULES: PluginScheduleDecl[] = [];');
  });
});
