import { existsSync, mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { SovereignManifest } from '@sovereignfs/manifest';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  collectPluginEnv,
  duplicateApiProviders,
  pruneGeneratedEntries,
  pruneStalePluginIcons,
  renderPluginCapabilities,
  renderPluginEnv,
  renderRegistry,
  resolveComposeTargets,
  sortPluginEntries,
  type EnvDecl,
  type PluginEntry,
} from '../generate-registry';

function manifest(overrides: Partial<SovereignManifest> = {}): SovereignManifest {
  return {
    schemaVersion: 1,
    id: 'com.example.plugin',
    name: 'Example Plugin',
    version: '1.0.0',
    type: 'community',
    runtime: 'native',
    routePrefix: '/example',
    permissions: [],
    compatibility: { minPlatformVersion: '0.0.0' },
    ...overrides,
  };
}

function entry(dir: string, overrides: Partial<SovereignManifest> = {}): PluginEntry {
  return { dir, manifest: manifest(overrides) };
}

describe('resolveComposeTargets', () => {
  const dirs = {
    platformPluginsDir: '/tmp/runtime/app/(platform)/(plugins)',
    modalDir: '/tmp/runtime/app/(platform)/(plugins)/@modal',
    minimalDir: '/tmp/runtime/app/(minimal)',
  };

  it('rejects multi-segment route prefixes for overlay plugins', () => {
    const result = resolveComposeTargets(
      manifest({ id: 'com.example.overlay', shell: 'overlay', routePrefix: '/admin/reports' }),
      dirs,
    );

    expect(result.ok).toBe(false);
    expect(result.targets).toEqual([]);
    expect(result.error).toContain('multi-segment');
    expect(result.error).toContain('/admin/reports');
  });

  it('accepts multi-segment route prefixes for minimal plugins', () => {
    const result = resolveComposeTargets(
      manifest({ id: 'com.example.minimal', shell: 'minimal', routePrefix: '/kiosk/display' }),
      dirs,
    );

    expect(result.ok).toBe(true);
    expect(result.targets).toEqual(['/tmp/runtime/app/(minimal)/kiosk/display']);
  });
});

describe('plugin generation guards', () => {
  it('detects duplicate apiProvider manifests before route generation', () => {
    const duplicates = duplicateApiProviders([
      entry('a', { id: 'com.example.api-a', apiProvider: true }),
      entry('b', { id: 'com.example.api-b', apiProvider: true }),
      entry('c', { id: 'com.example.regular' }),
    ]);

    expect(duplicates.map((plugin) => plugin.id)).toEqual([
      'com.example.api-a',
      'com.example.api-b',
    ]);
  });

  it('sorts plugin manifests deterministically by manifest id', () => {
    const sorted = sortPluginEntries([
      entry('z-dir', { id: 'com.example.zeta' }),
      entry('a-dir', { id: 'com.example.alpha' }),
      entry('m-dir', { id: 'com.example.middle' }),
    ]);

    expect(sorted.map((plugin) => plugin.manifest.id)).toEqual([
      'com.example.alpha',
      'com.example.middle',
      'com.example.zeta',
    ]);
    expect(sorted.map((plugin) => plugin.dir)).toEqual(['a-dir', 'm-dir', 'z-dir']);
  });
});

describe('generated TypeScript artifacts', () => {
  it('renders the registry from sorted manifest order', () => {
    const sorted = sortPluginEntries([
      entry('z-dir', { id: 'com.example.zeta' }),
      entry('a-dir', { id: 'com.example.alpha' }),
    ]);

    const content = renderRegistry(sorted);

    expect(content).toContain('AUTO-GENERATED by scripts/generate-registry.ts');
    expect(content.indexOf('"id": "com.example.alpha"')).toBeLessThan(
      content.indexOf('"id": "com.example.zeta"'),
    );
  });

  it('renders plugin capabilities and all-granted capabilities deterministically', () => {
    const content = renderPluginCapabilities([
      entry('notes', {
        id: 'com.example.notes',
        capabilities: {
          'read-notes': { description: 'Read notes', defaultGrant: 'all' },
          'write-notes': { description: 'Write notes' },
        },
      }),
    ]);

    expect(content).toContain('"namespacedCap": "com.example.notes:read-notes"');
    expect(content).toContain('"namespacedCap": "com.example.notes:write-notes"');
    expect(content).toContain('"defaultGrant": "none"');
    expect(content).toContain(
      'export const ALL_GRANTED_PLUGIN_CAPS: string[] = [\n  "com.example.notes:read-notes"\n];',
    );
  });
});

describe('plugin env generation', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-env-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('does not embed secret env default values in generated output', () => {
    const content = renderPluginEnv([
      {
        pluginId: 'com.example.secret',
        key: 'TOKEN',
        namespacedKey: 'SV_PLUGIN_COM_EXAMPLE_SECRET_TOKEN',
        required: true,
        secret: true,
        scope: 'runtime',
        defaultValue: 'do-not-embed',
      },
    ]);

    expect(content).toContain('"secret": true');
    expect(content).toContain('"SV_PLUGIN_COM_EXAMPLE_SECRET_TOKEN"');
    expect(content).not.toContain('do-not-embed');
  });

  it('uses plugin .env values only as non-secret dev defaults', () => {
    mkdirSync(join(root, 'notes'));
    writeFileSync(join(root, 'notes', '.env'), 'PUBLIC_LABEL=Local label\nTOKEN=plain-secret\n');

    const allowed = collectPluginEnv(
      [
        entry('notes', {
          id: 'com.example.notes',
          env: {
            PUBLIC_LABEL: {
              description: 'Development label',
              scope: 'runtime',
            },
          },
        }),
      ],
      root,
    );

    expect(allowed.ok).toBe(true);
    expect(allowed.decls).toMatchObject([
      {
        pluginId: 'com.example.notes',
        key: 'PUBLIC_LABEL',
        defaultValue: 'Local label',
        secret: false,
      } satisfies Partial<EnvDecl>,
    ]);

    const rejected = collectPluginEnv(
      [
        entry('notes', {
          id: 'com.example.notes',
          env: {
            TOKEN: {
              description: 'Secret token',
              required: true,
              secret: true,
              scope: 'runtime',
            },
          },
        }),
      ],
      root,
    );

    expect(rejected.ok).toBe(false);
    expect(rejected.error).toContain('marked secret');
    expect(rejected.error).toContain('plugins/notes/.env');
  });
});

describe('generated artifact pruning', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'generate-registry-prune-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('prunes stale generated routes while preserving active and committed entries', () => {
    mkdirSync(join(root, 'active'));
    mkdirSync(join(root, 'stale'));
    writeFileSync(join(root, 'layout.tsx'), 'layout');

    pruneGeneratedEntries(root, new Set(['active']), { keep: new Set(['layout.tsx']) });

    expect(existsSync(join(root, 'active'))).toBe(true);
    expect(existsSync(join(root, 'layout.tsx'))).toBe(true);
    expect(existsSync(join(root, 'stale'))).toBe(false);
  });

  it('prunes only stale generated modal routes', () => {
    mkdirSync(join(root, '(.)active'));
    mkdirSync(join(root, '(.)stale'));
    writeFileSync(join(root, 'default.tsx'), 'default');

    pruneGeneratedEntries(root, new Set(['(.)active']), { onlyPrefix: '(.)' });

    expect(existsSync(join(root, '(.)active'))).toBe(true);
    expect(existsSync(join(root, 'default.tsx'))).toBe(true);
    expect(existsSync(join(root, '(.)stale'))).toBe(false);
  });

  it('prunes stale generated plugin icons', () => {
    writeFileSync(join(root, 'com.example.active.svg'), '<svg />');
    writeFileSync(join(root, 'com.example.stale.svg'), '<svg />');

    pruneStalePluginIcons(root, new Set(['com.example.active']));

    expect(existsSync(join(root, 'com.example.active.svg'))).toBe(true);
    expect(existsSync(join(root, 'com.example.stale.svg'))).toBe(false);
  });
});
