/**
 * generate-theme-presets-css — emits `theme-presets.css` from the single
 * source of truth in `packages/ui/src/tokens/theme-presets.ts` (RFC 0094).
 *
 * Only for Storybook and standalone (non-runtime) consumers. The live
 * runtime instance-delivery path (RFC 0095, `runtime/src/instance-style.ts`)
 * imports `THEME_PRESETS` directly as a TS object — it never reads this
 * generated CSS file, so there is exactly one place these values are
 * authored.
 *
 * The generated selectors compose with `[data-theme='dark']` rather than
 * replacing it, and must always be set on the document root element
 * (`<html>`) — never a nested/scoped wrapper — because at least one override
 * (`--sv-radius-scale`) is the root of a `calc()` chain (`--sv-radius-sm`
 * through `-3xl`) declared once at `:root`; overriding it anywhere but
 * `:root` itself leaves those dependent tokens unchanged. See the doc
 * comment on `THEME_PRESETS` and `.storybook/preview.ts`'s `withRadius`
 * decorator for the same constraint.
 *
 * Run: `pnpm generate:theme-presets`
 * Add a preset: add it to `THEME_PRESETS` in `theme-presets.ts`, then re-run.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { THEME_PRESETS, type ThemePresetName } from '../packages/ui/src/tokens/theme-presets.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_FILE = join(ROOT, 'packages/ui/src/tokens/theme-presets.css');

function renderBlock(selector: string, tokens: Record<string, string>): string {
  const lines = Object.entries(tokens)
    .map(([token, value]) => `  ${token}: ${value};`)
    .join('\n');
  return `${selector} {\n${lines}\n}`;
}

function renderPreset(name: ThemePresetName): string {
  if (name === 'default') return ''; // empty overrides — nothing to emit
  const preset = THEME_PRESETS[name];
  const blocks = [renderBlock(`[data-theme-preset='${name}']`, preset.light)];
  if (Object.keys(preset.dark).length > 0) {
    blocks.push(renderBlock(`[data-theme-preset='${name}'][data-theme='dark']`, preset.dark));
  }
  return blocks.join('\n\n');
}

const presetBlocks = (Object.keys(THEME_PRESETS) as ThemePresetName[])
  .map(renderPreset)
  .filter(Boolean);

const output = `/*
 * Generated by scripts/generate-theme-presets-css.ts — do not edit.
 * Source of truth: packages/ui/src/tokens/theme-presets.ts
 *
 * For Storybook / standalone (non-runtime) use only — set data-theme-preset
 * on the document root element (<html>), never a nested wrapper. See the
 * generator script's doc comment for why.
 */
${presetBlocks.join('\n\n')}
`;

writeFileSync(OUT_FILE, output);
console.log(`[generate-theme-presets-css] wrote ${OUT_FILE}`);
