/**
 * generate-icons — generates inline RSC-safe SVG React components from Lucide.
 *
 * Reads the curated icon list in `scripts/icon-list.ts`, imports the icon data
 * from the `lucide` package (a devDependency — never a runtime/peer dep), and
 * emits one `.tsx` file per icon plus a barrel `index.ts` into
 * `packages/ui/src/components/Icon/icons/`.
 *
 * The generated files are committed source — they define what ships in the
 * published package. `lucide` itself does not ship.
 *
 * Run: `pnpm generate:icons`
 * Add icon: add the name to `scripts/icon-list.ts`, then re-run.
 *
 * Lucide license: ISC — see `packages/ui/NOTICE`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_LIST, type IconName } from './icon-list.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'packages', 'ui', 'src', 'components', 'Icon', 'icons');

/** "trash-2" → "Trash2", "chevron-right" → "ChevronRight" */
function toPascalCase(name: string): string {
  return name
    .split('-')
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('');
}

/** "trash-2" → "Trash2Icon" */
function toComponentName(name: IconName): string {
  return `${toPascalCase(name)}Icon`;
}

/** SVG attribute key → React JSX camelCase prop ("stroke-width" → "strokeWidth"). */
function toJsxProp(key: string): string {
  return key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** Render a single inner SVG element as a JSX self-closing string. */
function renderElement(tag: string, attrs: Record<string, string>): string {
  const props = Object.entries(attrs)
    .map(([k, v]) => `${toJsxProp(k)}="${v}"`)
    .join(' ');
  return props ? `      <${tag} ${props} />` : `      <${tag} />`;
}

/** Full TSX file content for a single icon. */
function iconFile(name: IconName, elements: [string, Record<string, string>][]): string {
  const component = toComponentName(name);
  const body = elements.map(([tag, attrs]) => renderElement(tag, attrs)).join('\n');
  return `// Generated by scripts/generate-icons.ts — do not edit.
// Source: Lucide (https://lucide.dev) — ISC license, see packages/ui/NOTICE.
import type { SVGProps } from 'react';

export function ${component}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
${body}
    </svg>
  );
}
`;
}

/** Barrel index.ts — imports, re-exports, IconName union, and ICONS map. */
function indexFile(names: readonly IconName[]): string {
  const imports = names.map((n) => `import { ${toComponentName(n)} } from './${n}';`).join('\n');
  const nameUnion = names.map((n) => `  | '${n}'`).join('\n');
  const mapEntries = names.map((n) => `  '${n}': ${toComponentName(n)},`).join('\n');
  const reExports = names.map((n) => `export { ${toComponentName(n)} } from './${n}';`).join('\n');

  return `// Generated by scripts/generate-icons.ts — do not edit.
import type { ReactElement, SVGProps } from 'react';
${imports}

export type IconName =
${nameUnion};

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement;

export const ICONS: Record<IconName, IconComponent> = {
${mapEntries}
};

${reExports}
`;
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const lucide = (await import('lucide')) as Record<string, unknown>;

  for (const name of ICON_LIST) {
    const exportName = toPascalCase(name);
    const data = lucide[exportName] as [string, Record<string, string>][] | undefined;
    if (!data) {
      console.error(`[generate-icons] icon not found in lucide: "${name}" (tried "${exportName}")`);
      process.exit(1);
    }
    writeFileSync(join(OUT_DIR, `${name}.tsx`), iconFile(name, data));
    console.log(`  ✓ ${name}`);
  }

  writeFileSync(join(OUT_DIR, 'index.ts'), indexFile(ICON_LIST));
  console.log(
    `\n[generate-icons] ${String(ICON_LIST.length)} icons → packages/ui/src/components/Icon/icons/`,
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
