/**
 * generate-registry — composes installed plugins into the runtime.
 *
 * Scans `plugins/<dir>/manifest.json`, validates each via `@sovereignfs/manifest`,
 * writes the typed plugin registry to `runtime/generated/registry.ts`, and copies
 * each plugin's `app/` into the runtime App Router at its `routePrefix`. An
 * invalid manifest fails the build.
 *
 * Copies, not symlinks, in every environment: Next's dev route watcher does not
 * follow symlinked route directories, so a symlinked plugin would 404 under
 * `next dev` (it works under `next build`, which does follow them). Copying
 * keeps dev and prod identical. The dev orchestrator (`scripts/dev.ts`) runs
 * this in `--watch` mode so edits under `plugins/` re-copy and trigger HMR.
 *
 * Composition target is chosen by the manifest `shell` value so the plugin
 * inherits the right layout from the route tree (no per-request branching):
 *   - `default` (or omitted) → `runtime/app/(platform)/(plugins)/<routePrefix>/`,
 *     which sits under the platform sidebar shell.
 *   - `minimal` → not yet implemented (a chrome-free group lands with the first
 *     minimal plugin); the script fails loudly rather than mis-composing one.
 *
 * The route segment is the manifest `routePrefix` (not the source directory
 * name), so `routePrefix` is the single source of truth for a plugin's URL.
 *
 * Run via `pnpm generate`; the runtime dev script runs it before `next dev`.
 * Pass `--watch` to re-run when plugin directories are added or removed.
 *
 * See: SRS §3.9 Plugin Loading Model.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  watch,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findApiProvider, validateManifest, type SovereignManifest } from '@sovereignfs/manifest';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PLUGINS_DIR = join(ROOT, 'plugins');
// Default-shell plugins compose under the platform route group so they inherit
// the sidebar shell. `(plugins)` is a URL-transparent route group; the public
// path is the plugin's routePrefix.
const PLATFORM_PLUGINS_DIR = join(ROOT, 'runtime', 'app', '(platform)', '(plugins)');
const REGISTRY_FILE = join(ROOT, 'runtime', 'generated', 'registry.ts');

interface PluginEntry {
  dir: string;
  manifest: SovereignManifest;
}

function readPlugins(): PluginEntry[] {
  if (!existsSync(PLUGINS_DIR)) return [];
  const plugins: PluginEntry[] = [];

  for (const entry of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifestPath = join(PLUGINS_DIR, entry.name, 'manifest.json');
    if (!existsSync(manifestPath)) continue;

    let json: unknown;
    try {
      json = JSON.parse(readFileSync(manifestPath, 'utf8'));
    } catch (error) {
      console.error(
        `[generate] ${relative(ROOT, manifestPath)} is not valid JSON: ${(error as Error).message}`,
      );
      process.exit(1);
    }

    const result = validateManifest(json);
    if (!result.valid) {
      console.error(`[generate] invalid manifest ${relative(ROOT, manifestPath)}:`);
      for (const message of result.errors) console.error(`  - ${message}`);
      process.exit(1);
    }

    plugins.push({ dir: entry.name, manifest: result.manifest });
  }

  plugins.sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));

  // PLT-16: at most one plugin may serve the public /api/* namespace. Fail
  // loudly rather than picking one non-deterministically at request time.
  const { duplicates } = findApiProvider(plugins.map((p) => p.manifest));
  if (duplicates.length > 1) {
    console.error(
      '[generate] more than one plugin declares apiProvider: true — exactly one ' +
        'API provider is allowed per instance (PLT-16):',
    );
    for (const m of duplicates) console.error(`  - ${m.id}`);
    process.exit(1);
  }

  return plugins;
}

function writeRegistry(plugins: PluginEntry[]): void {
  mkdirSync(dirname(REGISTRY_FILE), { recursive: true });
  const manifests = plugins.map((p) => p.manifest);
  const content = `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
import type { SovereignManifest } from '@sovereignfs/manifest';

export const registry: SovereignManifest[] = ${JSON.stringify(manifests, null, 2)};
`;
  writeFileSync(REGISTRY_FILE, content);
}

/** Route group a plugin composes into, chosen by its `shell` mode. */
function targetGroupDir(manifest: SovereignManifest): string {
  const shell = manifest.shell ?? 'default';
  if (shell === 'minimal') {
    console.error(
      `[generate] plugin ${manifest.id} declares shell: "minimal", which is not yet ` +
        'supported — a chrome-free route group lands with the first minimal plugin.',
    );
    process.exit(1);
  }
  return PLATFORM_PLUGINS_DIR;
}

// Every route group plugins may compose into. Listed so each is cleared before
// composition; `(fullscreen)` for minimal-shell plugins is added when needed.
const GROUP_DIRS = [PLATFORM_PLUGINS_DIR];

function composePlugins(plugins: PluginEntry[]): void {
  // Remove previously composed plugins from every group (keep each .gitignore).
  for (const groupDir of GROUP_DIRS) {
    mkdirSync(groupDir, { recursive: true });
    for (const entry of readdirSync(groupDir)) {
      if (entry === '.gitignore') continue;
      rmSync(join(groupDir, entry), { recursive: true, force: true });
    }
  }

  for (const { dir, manifest } of plugins) {
    const srcApp = join(PLUGINS_DIR, dir, 'app');
    if (!existsSync(srcApp)) continue;
    // The public path is the manifest routePrefix, not the source dir name.
    const routeSegment = manifest.routePrefix.replace(/^\/+/, '');
    const dest = join(targetGroupDir(manifest), routeSegment);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(srcApp, dest, { recursive: true });
  }
}

function generate(): void {
  const plugins = readPlugins();
  writeRegistry(plugins);
  composePlugins(plugins);
  console.log(`[generate] ${String(plugins.length)} plugin(s) composed.`);
}

generate();

if (process.argv.includes('--watch')) {
  console.log('[generate] watching plugins/ for changes…');
  let timer: NodeJS.Timeout | undefined;
  watch(PLUGINS_DIR, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(generate, 150);
  });
}
