import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { DEFAULT_TENANT_ID, enqueueBackupJob } from '@sovereignfs/db';
import { logActivity } from '@/src/activity';
import { backupArchivePathForJob } from '@/src/backup-download';
import { storeBackupPassphrase } from '@/src/backup-passphrase-store';
import { getPlatformDb } from '@/src/db';

const MIN_PASSPHRASE_LENGTH = 8;

/**
 * Enqueue an async, selective, passphrase-encrypted backup of the current
 * user's own data (RFC 0084, epic task 8.18). Returns immediately with a
 * job id — the archive is generated by `runtime/src/backup-worker.ts`'s
 * next tick, not in this request. Requires `SOVEREIGN_BACKUP_WORKER_ENABLED`
 * to actually be picked up; the job otherwise just sits `queued` forever,
 * which is a deployment/config concern, not something this route enforces.
 */
export async function POST(request: Request): Promise<Response> {
  const userId = request.headers.get('x-sovereign-user-id');
  if (!userId) return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });

  const body = (await request.json().catch(() => null)) as {
    passphrase?: unknown;
    includeFiles?: unknown;
    excludePluginIds?: unknown;
  } | null;

  const passphrase = typeof body?.passphrase === 'string' ? body.passphrase : '';
  if (passphrase.length < MIN_PASSPHRASE_LENGTH) {
    return NextResponse.json(
      { error: `Passphrase must be at least ${String(MIN_PASSPHRASE_LENGTH)} characters.` },
      { status: 400 },
    );
  }

  const includeFiles = body?.includeFiles !== false;
  const excludePluginIds = Array.isArray(body?.excludePluginIds)
    ? body.excludePluginIds.filter((id): id is string => typeof id === 'string')
    : undefined;

  const jobId = randomUUID();
  const archivePath = backupArchivePathForJob(jobId, 'user');
  const pdb = await getPlatformDb();
  const job = await enqueueBackupJob(pdb, {
    id: jobId,
    tenantId: DEFAULT_TENANT_ID,
    scope: 'user',
    requestedByUserId: userId,
    archivePath,
    optionsJson: JSON.stringify({ includeFiles, excludePluginIds }),
  });

  // Stored only after the row exists, so a crash between the two never
  // leaves a passphrase in memory for a job that was never actually queued.
  storeBackupPassphrase(job.id, passphrase);

  void logActivity({
    actorId: userId,
    actorType: 'user',
    action: 'account.backup_requested',
    visibility: 'user',
    summary: 'Requested a full account backup',
  });

  return NextResponse.json({ jobId: job.id }, { status: 202 });
}
