import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { DEFAULT_TENANT_ID, enqueueBackupJob, getPluginConnection } from '@sovereignfs/db';
import { logActivity } from '@/src/activity';
import { backupArchivePathForJob } from '@/src/backup-download';
import { storeBackupPassphrase } from '@/src/backup-passphrase-store';
import { getPlatformDb } from '@/src/db';

const MIN_PASSPHRASE_LENGTH = 8;

// Matches plugins/account/app/_lib/backup-destinations.ts's PROVIDER_KIND
// owner — backup destinations are always created under the account plugin's
// own id, regardless of which route later reads them back.
const BACKUP_DESTINATION_PLUGIN_ID = 'fs.sovereign.account';

/**
 * Enqueue an async, selective, passphrase-encrypted backup of the current
 * user's own data (RFC 0084, epic task 8.18). Returns immediately with a
 * job id — the archive is generated by `runtime/src/backup-worker.ts`'s
 * next tick, not in this request. Requires `SOVEREIGN_BACKUP_WORKER_ENABLED`
 * to actually be picked up; the job otherwise just sits `queued` forever,
 * which is a deployment/config concern, not something this route enforces.
 */
export async function POST(request: Request): Promise<Response> {
  const userId = request.headers.get('x-sovereign-user-id');
  if (!userId) return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });

  const body = (await request.json().catch(() => null)) as {
    passphrase?: unknown;
    includeFiles?: unknown;
    excludePluginIds?: unknown;
    pushDestinationId?: unknown;
  } | null;

  const passphrase = typeof body?.passphrase === 'string' ? body.passphrase : '';
  if (passphrase.length < MIN_PASSPHRASE_LENGTH) {
    return NextResponse.json(
      { error: `Passphrase must be at least ${String(MIN_PASSPHRASE_LENGTH)} characters.` },
      { status: 400 },
    );
  }

  const includeFiles = body?.includeFiles !== false;
  const excludePluginIds = Array.isArray(body?.excludePluginIds)
    ? body.excludePluginIds.filter((id): id is string => typeof id === 'string')
    : undefined;

  const pdb = await getPlatformDb();

  const pushDestinationId =
    typeof body?.pushDestinationId === 'string' && body.pushDestinationId.length > 0
      ? body.pushDestinationId
      : undefined;
  if (pushDestinationId) {
    // Fail fast with a clear 400 for an unknown/foreign/disconnected
    // destination, rather than letting the job queue and only discover this
    // much later on the worker's own tick — runUserBackup() re-checks this
    // independently regardless, since that's the actual authorization
    // boundary, not this convenience check.
    const connection = await getPluginConnection(pdb, pushDestinationId, {
      tenantId: DEFAULT_TENANT_ID,
      pluginId: BACKUP_DESTINATION_PLUGIN_ID,
      userId,
    });
    if (!connection || connection.status === 'disconnected') {
      return NextResponse.json({ error: 'Backup destination not found.' }, { status: 400 });
    }
  }

  const jobId = randomUUID();
  const archivePath = backupArchivePathForJob(jobId, 'user');
  const job = await enqueueBackupJob(pdb, {
    id: jobId,
    tenantId: DEFAULT_TENANT_ID,
    scope: 'user',
    requestedByUserId: userId,
    archivePath,
    optionsJson: JSON.stringify({ includeFiles, excludePluginIds, pushDestinationId }),
  });

  // Stored only after the row exists, so a crash between the two never
  // leaves a passphrase in memory for a job that was never actually queued.
  storeBackupPassphrase(job.id, passphrase);

  void logActivity({
    actorId: userId,
    actorType: 'user',
    action: 'account.backup_requested',
    visibility: 'user',
    summary: 'Requested a full account backup',
  });

  return NextResponse.json({ jobId: job.id }, { status: 202 });
}
